services:
  jatidp:
    build: .
    container_name: jatidp
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wridp.rule=Host(`idp.flask_idp.localhost`)"
      - "traefik.http.routers.wridp.tls=true"
      - "traefik.http.routers.wridp.entrypoints=websecure"
    depends_on:
      - jatidp_db
    networks:
      - proxy

  jatidp_db:
    image: mariadb:latest
    container_name: jatidp_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3323:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true
